---
services:
  flask:
    image: rhosrow/flask:latest
    build:
      context: flask
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - ./flask/dev.env
    secrets:
      - api_key
      - source: api_key
        target: /api_key.txt
    configs:
      - source: my_config
        target: /config-dev-v2.yaml
    environment:
      - APP_VERSION=0.1.0
      - DB_PASSWORD
      - APP_TOKEN=${APP_TOKEN}
    volumes:
      - ./flask/config.dev.yaml:/config-dev.yaml
    
secrets:
  api_key: 
    file: ./flask/api_key.txt

configs:
  my_config:
    file: ./flask/config.dev.yaml